
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 24 00:44:01 IDT 2018
//----------------------------------------------------

package jminor.ast;

/** CUP generated class containing symbol constants. */
public class JminorSym {
  /* terminals */
  public static final int GHOST = 8;
  public static final int DIVIDE = 37;
  public static final int SEMI = 13;
  public static final int BOOLEAN_VAL = 38;
  public static final int MINUS = 35;
  public static final int STMT_LIST = 41;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int LT = 27;
  public static final int TYPE = 2;
  public static final int LP = 19;
  public static final int OR = 32;
  public static final int ELLIPSIS = 18;
  public static final int COMMA = 12;
  public static final int RP = 20;
  public static final int GEQ = 30;
  public static final int PLUS = 34;
  public static final int ASSIGN = 15;
  public static final int IF = 9;
  public static final int ID = 40;
  public static final int MUT = 7;
  public static final int DOT = 14;
  public static final int INT_VAL = 39;
  public static final int EOF = 0;
  public static final int LB = 21;
  public static final int TEST = 6;
  public static final int error = 1;
  public static final int RB = 22;
  public static final int NULL = 4;
  public static final int NEQ = 26;
  public static final int EXAMPLE = 5;
  public static final int EQ = 25;
  public static final int LCB = 23;
  public static final int TIMES = 36;
  public static final int ARROW = 17;
  public static final int COLON = 16;
  public static final int ELSE = 11;
  public static final int WHILE = 10;
  public static final int LEQ = 28;
  public static final int RCB = 24;
  public static final int GT = 29;
  public static final int VAR = 3;
}

