
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 12 20:03:39 IST 2017
//----------------------------------------------------

package heap.ast;

/** CUP generated class containing symbol constants. */
public class HeapSym {
  /* terminals */
  public static final int LP = 9;
  public static final int COLON = 7;
  public static final int INT_VAL = 13;
  public static final int LCB = 11;
  public static final int NULL = 4;
  public static final int EOF = 0;
  public static final int ARROW = 8;
  public static final int VAR = 3;
  public static final int EXAMPLE = 5;
  public static final int TYPE = 2;
  public static final int ID = 14;
  public static final int RCB = 12;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int RP = 10;
}

