
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 26 12:46:32 IDT 2018
//----------------------------------------------------

package heap.ast;

/** CUP generated class containing symbol constants. */
public class HeapSym {
  /* terminals */
  public static final int TIMES = 29;
  public static final int AND = 25;
  public static final int LT = 24;
  public static final int ELSE = 10;
  public static final int PLUS = 27;
  public static final int OR = 26;
  public static final int LP = 17;
  public static final int SEMI = 12;
  public static final int WHILE = 9;
  public static final int RP = 18;
  public static final int IF = 8;
  public static final int COLON = 15;
  public static final int ID = 32;
  public static final int LCB = 21;
  public static final int LB = 19;
  public static final int EXAMPLE = 5;
  public static final int RB = 20;
  public static final int TYPE = 2;
  public static final int COMMA = 11;
  public static final int EOF = 0;
  public static final int DIVIDE = 30;
  public static final int MINUS = 28;
  public static final int GHOST = 7;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int ARROW = 16;
  public static final int MUT = 6;
  public static final int INT_VAL = 31;
  public static final int EQ = 23;
  public static final int RCB = 22;
  public static final int ASSIGN = 14;
  public static final int NULL = 4;
  public static final int VAR = 3;
}

