
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 21 00:24:27 IST 2017
//----------------------------------------------------

package heap.ast;

/** CUP generated class containing symbol constants. */
public class HeapSym {
  /* terminals */
  public static final int AND = 11;
  public static final int LP = 14;
  public static final int RP = 15;
  public static final int COLON = 12;
  public static final int ID = 19;
  public static final int LCB = 16;
  public static final int EXAMPLE = 5;
  public static final int TYPE = 2;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int GHOST = 7;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int ARROW = 13;
  public static final int MUT = 6;
  public static final int INT_VAL = 18;
  public static final int RCB = 17;
  public static final int EQ = 10;
  public static final int NULL = 4;
  public static final int VAR = 3;
}

